### PR TITLE
Added '-depth' '-flatten' and '-colorspace' options

### PR DESCRIPTION
**Pull request by 70mmy**

### CODE REVIEW

**Comment by Pierstoval** [comment]
Perfect PR! Can you add the options to the `Currently supported options` list in the README file? 😄

**Comment by 70mmy** [comment]
Thanks! Disappointed in myself that I have not thought of that. Updated the README as well.

**Comment by Pierstoval** [comment]
Thank you very much for your contribution 👍

**Comment by Pierstoval** [comment]
Released in v3.0.9 😄

**Comment by 70mmy** [comment]
Thanks!

**Pull request merged**
