### PR TITLE
Try Php 8

### LINKED ISSUE #26: Compatibility with PHP 8
Hey @Pierstoval, long time no see (thanks for your excellent Symfony lessons last year 😃) !

We are very interested in this library for our project but we are wondering : what is needed to make it compatible with PHP8 ?

### PR DESCRIPTION
**Pull request by VincentLanglet**
Close https://github.com/Orbitale/ImageMagickPHP/issues/26

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@Pierstoval The PR seems ready to merge with php 8 compatibility.

**Comment by Pierstoval** [comment]
Is there no way to keep PHP 7.1 compatibility?

**Comment by VincentLanglet** [comment]
> Is there no way to keep PHP 7.1 compatibility?

Didn't try, you were not 7.1-compatible.
https://github.com/Orbitale/ImageMagickPHP/blob/main/composer.json#L16

I just updated the readme.

**Comment by Pierstoval** [comment]
Indeed, good catch 😉

**Review by Pierstoval — APPROVED** [review]

**Comment by Pierstoval** [comment]
Thanks @VincentLanglet 👍

**Comment by VincentLanglet** [comment]
You're welcome !

Do you mind creating a new release with this official support of php 8 ?

**Comment by Pierstoval** [comment]
Will do :)

**Comment by Pierstoval** [comment]
Done in [v3.0.14](https://github.com/Orbitale/ImageMagickPHP/releases/tag/v3.0.14)

**Pull request merged**
