### PR TITLE
Support Symfony 7

### PR DESCRIPTION
**Pull request by derrabus**

### CODE REVIEW

**Comment by derrabus** [comment]
Apparently, the CI has been disabled on this repository. I've run the tests locally on PHP 8.3 and they pass.

**Review by Pierstoval — APPROVED** [review]
Ran locally with 8.2 and 8.3 and works too 👌 Thanks @derrabus!

**Comment by Pierstoval** [comment]
Apparently for the CI, the Docker image that I was using to make it work is no longer available, I need to rebuild it and make it work again, it's going to take some time.

**Comment by Pierstoval** [comment]
CI is fixed 👍 https://github.com/Orbitale/ImageMagickPHP/actions/runs/7259336396

**Comment by derrabus** [comment]
Thank you!

**Pull request merged**
